### PR TITLE
Add YAML support for GPDS

### PR DESCRIPTION
**Pull request by vowstar**
### Changelog summary

- Add a lightweight miniyaml library whose license is MIT and compatible with GPDS
- Added the implementation of archiver_yaml without breaking the API of GPDS
- Achieve code compatibility with old projects
- Added YAML-related test code and passed the test
- Modify readme to reflect support for YAML

### List of new testsuits and pass status

- [x] 25_deserialize_booleans_yaml.cpp
- [x] 26_deserialize_integer_yaml.cpp
- [x] 27_deserialize_floats_yaml.cpp
- [x] 28_deserialize_strings_yaml.cpp
- [x] 29_deserialize_attributes_yaml.cpp
- [x] 30_deserialize_container_attributes_yaml.cpp
- [x] 37_deserializing_empty_container_yaml.cpp
- [x] 38_load_and_save_file_yaml.cpp

```bash
"doctest" start time: Jul 08 20:28 CST
Output:
----------------------------------------------------------
[doctest] doctest version is "2.4.10"
[doctest] run with "--help" for options
===============================================================================
[doctest] test cases:  46 |  46 passed | 0 failed | 0 skipped
[doctest] assertions: 290 | 290 passed | 0 failed |
[doctest] Status: SUCCESS!
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Passed.
"doctest" end time: Jul 08 20:28 CST
"doctest" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Jul 08 20:28 CST
```

### CODE REVIEW

**Comment by Tectu** [comment]
Thanks!
I'll have a closer look in the next few days :)

**Comment by Tectu** [comment]
Thank you for your contribution!

I think we'll extend the `serialize` interface to simply provide a function template accepting the archiver type. By default, we'll use the XML archiver to provide API compatibility as you did too.

**Comment by Tectu** [comment]
@vowstar I've updated the `serialize` interface. It should be entirely transparent but the current interface is now marked deprecated. The way to go moving forward is using the various free-standing function templates:

- `gpds::to_string()`
- `gpds::from_string()`
- `gpds::to_file()`
- `gpds::from_file()`

These accept the archiver to use (eg `archiver_xml` or your newly introduced `archiver_yaml`) via template parameter making things notably nicer. Adding new archivers will no longer require jumping through a lot of hoops like you were forced to such as introducing the "mode" enum :)

You might want to upgrade your code now that this was merged & the interface was updated to ensure you don't use the deprecated functions anymore.
An example can be found in the release notes: https://github.com/simulton/gpds/releases/tag/1.6.0

**Comment by vowstar** [comment]
Thank you very much, this is very elegant!

**Pull request merged**
